channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:

    # Example command line software
    - snakemake
    - cutadapt=3.5
    - nextflow=22.10.1
    - pigz=2.6
    - seqtk=1.3
    - fastqc=0.11.9
    - bbmap=39.01
    - multiqc=1.12
    - samtools=1.16.1
    - bwa=0.7.17

    # Example Python packages
    - python 
    - argparse=1.4.0

    # Example R packages
    - r-base=4.2.2
    - r-tidyverse=1.3.2
